using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Jellyfin.Plugin.SmartSpotifyPlaylists.Models;

/// <summary>
/// Represents a mood/genre cluster generated by OpenAI.
/// </summary>
public class VibeCluster
{
    /// <summary>
    /// Gets or sets the cluster name (e.g., "Upbeat Pop", "Melancholic Lo-Fi").
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the cluster description.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the list of Jellyfin item IDs that belong to this cluster.
    /// </summary>
    public List<string> TrackIdentifiers { get; set; } = new();
}

/// <summary>
/// Response model for cluster generation from OpenAI.
/// </summary>
public class ClusterGenerationResponse
{
    /// <summary>
    /// Gets or sets the list of generated clusters.
    /// </summary>
    public List<VibeCluster> Clusters { get; set; } = new();
}

/// <summary>
/// Response model for track assignment from OpenAI.
/// </summary>
public class AssignmentResponse
{
    /// <summary>
    /// Gets or sets the list of cluster assignments.
    /// </summary>
    public List<ClusterAssignment> Assignments { get; set; } = new();
}

/// <summary>
/// Represents assignment of tracks to a cluster.
/// </summary>
public class ClusterAssignment
{
    /// <summary>
    /// Gets or sets the cluster index (0-based).
    /// </summary>
    [JsonPropertyName("cluster_index")]
    public int ClusterIndex { get; set; }

    /// <summary>
    /// Gets or sets the list of song indices assigned to this cluster.
    /// </summary>
    [JsonPropertyName("song_indices")]
    public List<int> SongIndices { get; set; } = new();
}
